# http://docs.travis-ci.com/user/languages/go/
language: go

go:
  - 1.2.1

branches:
  only:
    - master

# http://docs.travis-ci.com/user/languages/go/#Dependency-Management
install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/garyburd/redigo/redis
  - go get github.com/codegangsta/martini
  - go get github.com/golang/glog

# http://docs.travis-ci.com/user/database-setup/#Redis
services:
  - redis-server
