# http://docs.travis-ci.com/user/languages/go/
language: go

go:
  - 1.2.1

branches:
  only:
    - go-lang

# http://docs.travis-ci.com/user/languages/go/#Dependency-Management
install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/alphazero/Go-Redis

# http://docs.travis-ci.com/user/database-setup/#Redis
services:
  - redis-server
