# http://docs.travis-ci.com/user/languages/go/
language: go

go:
  - 1.2.1

script: go test opensemanticapi/tests

branches:
  only:
    - go-lang

# http://docs.travis-ci.com/user/database-setup/#Redis
services:
  - redis-server
